### ISSUE TITLE
Document reasons for choosing default extensions?

### ISSUE THREAD

**Issue by shapr** [JonathanLorimer/templates#7]
I turn off `NoImplicitPrelude` and `StrictData` in the projects that I generate from this flake, but now I wonder if I'm missing something.

Is there any discussion/description on why these are enabled by default?

**Comment by JonathanLorimer** [comment]
I think I was just enabling pragmas that I use almost universally, I am fine with turning them off!

**Comment by solomon-b** [comment]
What if we redid the FZF interface using `gum` and did a multiselect thing for pragmas and libraries?

https://github.com/charmbracelet/gum#choose

**Comment by JonathanLorimer** [comment]
Great idea @solomon-b, closing in favour of #14
